### ISSUE TITLE
Side drawer screen

### ISSUE THREAD

**Issue by ThomasFSynnes** [ThomasFSynnes/IDATA2023_Group8#13]
Side drawer with:
- log in/ create user
- add new manual
- app settings
- log out
- contact us

**Comment by giagiao** [comment]
Hi, I need some information for UI design requirements such as Colors, logo, project name, etc.

**Comment by ThomasFSynnes** [comment]
done

**Comment by Kim3n** [comment]
Need to fix overflow with bigger font size and hide upload button when not logged in
