### ISSUE TITLE
Add new manual

### ISSUE THREAD

**Issue by ThomasFSynnes** [ThomasFSynnes/IDATA2023_Group8#8]
Let a user add a new manual to the database.
user must be logged in to upload a a new manual

must have: 
- .pdf file
- product name (title) 

optional:
- category 
- manufacture
- product image (do we need to handle special characters in the URL?)

**Comment by Kim3n** [comment]
I have made a work in progress upload screen, the product image gets uploaded to firebase file storage and can be accessed with Image.network(), this has been tested and is working. I'll implement another upload for PDFs later

Currently the Product is saved locally in dummy data so will implement writing and reading from SQL database later 

Page currently looks like this:
![image](https://github.com/ThomasFSynnes/IDATA2023_Group8/assets/71408597/1d73310e-a0f8-4a0f-a68f-3175e3b1d717)
